### ISSUE TITLE
poco 

### ISSUE THREAD

**Issue by meethra666** [bostjan2016/HyperOS1-Slovenian#1]
ZDRAVO...EJGA, ZANIMA ME CE LAHKO ZRIHTAS KKSN RECOVERY ZA POCO C40 IN PRIPOROCIS KKSN CUSTOM ROM, KER TALE K JE ZJ GOR STEKA KO PR NORCIH...PISI MI NA samuelrezar@gmail.com    ps.: telefona se nism rootal. postopk poznam, le recoveryja ne najdem,.....LP Samo

**Comment by bostjan2016** [comment]
Ejga, napačno vprašanje na napačnem mestu.
Tukaj je prostor za javljanje napak v slo prevodu, ne za iskanje softwera. Temu so namenjeni forumi.

Kot sem pogledal po netu, mislim, da ne boš našel česar iščeš. Pač model fona prodan v tako majhni količini, da se nihče ne loti ustvarjanja kakih izboljšav.
Preden kupiš nasledni telefon preglej, kako možnosti boš imel z njim...
Lp Boštjan
